### PR TITLE
Added limit/offset clause

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Comment by sebersole** [comment]
Was there a Jira for this?

**Comment by beikov** [comment]
Here you go: https://hibernate.atlassian.net/browse/HHH-11474

**Comment by sebersole** [comment]
Would you mind rebasing your commit too to edit the commit message to include that Jira key?  That's how auto Jira linking of PRs and commits works

**Comment by beikov** [comment]
Done

**Pull request merged**
