### PR TITLE
Wip/6.0 update delete

### PR DESCRIPTION
**Pull request by dreab8**

### CODE REVIEW

**Comment by sebersole** [comment]
@dreab8 @Naros - I am working on integrating https://github.com/sebersole/hibernate-core/pull/147.  Does this one need applied as well?

**Comment by dreab8** [comment]
Hi @sebersole,

yes it needs to be applied.
I think  that changes I made in this PR and related to org.hibernate.sql.results.internal.domain.entity.AbstractEntityInitializer have to be discarded in favour of the last changes introduced by the work done on fetches.

**Comment by dreab8** [comment]
@sebersole , I'm working on integrating this.

**Comment by dreab8** [comment]
superseded by https://github.com/sebersole/hibernate-core/pull/149

**Pull request closed without merging**
