### PR TITLE
Wip/6.0 andrea onetoone

### PR DESCRIPTION
**Pull request by Naros**
Follow-up PR to #137

### CODE REVIEW

**Comment by sebersole** [comment]
@dreab8 Is this the one you are working to resolve and push a new PR for?

**Comment by dreab8** [comment]
@sebersole yes this PR contains few changes made by me and @Naros

**Comment by dreab8** [comment]
The part related with the UK loading are the `SingularPersistentAttributeEntity#resolveHydratedState `
with `StandardSingleUniqueKeyEntityLoader`

**Comment by sebersole** [comment]
I think we are going to have to integrate this sooner rather than later.  I am working on changes that also needs changes to how ForeignKeys (the Columns) are built.  So unfortunately this work and my local work dove-tail and probably conflict.

Monday I'd like to walk through integrating this PR with my local branch and getting the combination pushed.

**Comment by sebersole** [comment]
Applied to my local wip/6.0 - will push to repo once my work is done

**Pull request closed without merging**
