### PR TITLE
Wip/6.0 10954

### PR DESCRIPTION
**Pull request by dreab8**
not sure about AbstractSqmAggregateFunction.java and AbstractSqmFunction.java

### CODE REVIEW

**Comment by sebersole** [comment]
Not sure about them wrt `createQueryResult` impl?

**Comment by dreab8** [comment]
yeap

**Comment by dreab8** [comment]
if it is correct what I did

**Comment by sebersole** [comment]
That is exactly what I would expect given how we resolve SqlSelections atm.

**Pull request merged**
