### PR TITLE
Wip/6.0 PersistentCollectionTuplizer

### PR DESCRIPTION
**Pull request by dreab8**
before going further, @sebersole @Naros what do u think about the CollectionJTD returning the appropriate Tuplizer? 

one thing i do not like it's the AbstractCollectionJTD name to be used when checking if it is an "instance of";

### CODE REVIEW

**Comment by dreab8** [comment]
Thanks @sebersole for looking at the code.
A CollectionJavaDescriptor seemed to me, but probably I'm wrong and there is a better way, a good point to return the appropriate CollectionTuplizer.
I'll think a little more on this and sure we can discuss this in the next week video chat.

**Comment by sebersole** [comment]
It is actually not at all a good place to expose CollectionTuplizer.  

The JavaTypeDescriptor of any attribute is the descriptor of the Java type for that attribute.  E.g. the JTD for `Person#name` is `JTD<String>`.  In that same vein, the JTD for a plural attribute is simply the JTD for the exposed Java type, so `JTD<List>`, `JTD<Set>`, etc.  Just as there should only ever be one `JTD<String>` in our system, there should only ever be one `JTD<List>`, etc.

`CollectionTuplizer` is specific to a certain role.  Just like it would not be correct to keep the `AttributeConverter` (specific to a role) applied to `Person#name` as part of its `JTD<String>`, it is also not correct to keep collection-role-specific data (such as `CollectionTuplizer`) on the collection's JTD.  Doing so would mean that we'd have multiple `JTD<List>` instances, one for each List-valued plural-attribute.

The proper place to keep `CollectionTuplizer` is on the `PersistentCollectionDescriptor`. 

Also, if you are doing `instanceof` checks on the JTD to determine what "kind" of collection... have you seen `PersistentCollectionDescriptor#getCollectionClassification`?  It returns an enumeration over the actual kinds of plural attributes we support:

````
	/**
	 * Classifications of the plurality.  See {@link CollectionElement.ElementClassification}
	 * and {@link CollectionIndex.IndexClassification} for classification of the element and
	 * index/key, respectively.
	 */
	enum CollectionClassification {
		SET( PluralAttribute.CollectionType.SET ),
		LIST( PluralAttribute.CollectionType.LIST ),
		MAP( PluralAttribute.CollectionType.MAP ),
		BAG( PluralAttribute.CollectionType.COLLECTION );

		private final PluralAttribute.CollectionType jpaClassification;

		CollectionClassification(PluralAttribute.CollectionType jpaClassification) {
			this.jpaClassification = jpaClassification;
		}

		public PluralAttribute.CollectionType toJpaClassification() {
			return jpaClassification;
		}
	}
````
And I actually have some todo comments about some minor points in regards to CollectionClassification and its relation to `PersistentCollectionDescriptor`, `PersistentCollectionTuplizer` and `PersistentCollectionTuplizerFactory`.  Namely, `PersistentCollectionTuplizerFactory` currently is defined as:

````
    PersistentCollectionTuplizer getImplicitTuplizer(Class collectionJavaType);
````

But I am wondering if the following would be a better signature:

````
    PersistentCollectionTuplizer getImplicitTuplizer(CollectionClassification classification);
````

`CollectionClassification` would then logically be defined by the `PersistentCollectionTuplizer` rather than the `PersistentCollectionDescriptor`.  That is logical in many ways.

**Comment by dreab8** [comment]
Thanks for the detailed explanation, the  piece I'm missing :) is how to obtain the appropriate ```PersistentCollectionTuplizer``` implementation based on the the collectionJavaType or the ```CollectioClassification```.

By example  for a ```CollectionClassification.SET``` the ```PersistentCollectionTuplizer#instantiate(int anticipatedSize)``` has to instantiate a ```TreeSet``` if the set is sorted or a ```TreeSet``` if ordered or an ```HashSet```.
 For ```CollectionClassification.COLLECTION``` instead the  ```PersistentCollectionTuplizer#getPersistentCollectionJavaType()``` has to return a different ```PersistenCollection``` based on the fact it is a CollectionId or not.

By the way I prefer ` PersistentCollectionTuplizer getImplicitTuplizer(CollectionClassification classification);`

**Comment by sebersole** [comment]
> how to obtain the appropriate PersistentCollectionTuplizer implementation based on the the collectionJavaType or the CollectioClassification

Why would you want/need to?  What is the problem you are trying to solve?

Keep in mind that a user can explicitly tell us the `PersistentCollectionTuplizer` to use for a particular plural-attribute.  It's not like this is a one-to-one mapping from a certain "collection type" (LIST, SET, etc) to a certain PersistentCollectionTuplizer.  This follows how we allow custom entity and component tuplizers (see  `@org.hibernate.annotations.Tuplizer` e.g.)

**Comment by sebersole** [comment]
BTW, here is the complete set of todos I have for this locally:

````
public interface PersistentCollectionTuplizerFactory {

	// todo (6.0) : what about passing PersistentCollectionDescriptor.CollectionClassification, rather than the "collection type"?

	// todo (6.0) : any benefit to passing along the NavigableRole?
	//		- the idea being that the factory impl could be sensitive
	//			to each role, possibly through configuration via settings

	// todo (6.0) : relatedly ^^, anything else we should pass along?

	PersistentCollectionTuplizer getImplicitTuplizer(Class collectionJavaType);
}
````

**Comment by sebersole** [comment]
> By example for a CollectionClassification.SET the PersistentCollectionTuplizer#instantiate(int anticipatedSize) has to instantiate a TreeSet if the set is sorted or a TreeSet if ordered or an HashSet.
For CollectionClassification.COLLECTION instead the PersistentCollectionTuplizer#getPersistentCollectionJavaType() has to return a different PersistenCollection based on the fact it is a CollectionId or not.

Sorry I missed this section originally.  Basically I wonder if we need the full gambit here:

````
public enum CollectionClassification {
    LIST(...),
    SET(...),
    SORTED_SET(...),
    ORDERED_MAP(...),
    MAP(...),
    SORTED_MAP(...),
    ORDERED_MAP(...),
    BAG(...),
    IDBAG(...),
    ARRAY(...)
}
````
I think that makes a pretty complete set of options to `PersistentCollectionTuplizerFactory`, although I do wonder if we need to pass anything in addition to just this enumerated value.  I mentioned `NavigableRole`.  Maybe `RuntimeModelCreationContext`.  

WDYT?

**Comment by dreab8** [comment]
yes I think it's a complete set of options.
Related to passing ```NavigableRole``` and/or  ```RuntimeModelCreationContext``` no 100% sure but as you mentioned in your local TODO passing the ``NavigableRole`` seems to me really a good idea for config purposes.

**Comment by sebersole** [comment]
Should I close this?

**Comment by dreab8** [comment]
rejected

**Pull request closed without merging**
