### PR TITLE
HHH-12164 Upgrade Hibernate Validator used for testing to 6.0.6.Final

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/HHH-12164

I couldn't execute all the tests as it seems there is an issue testing the modules with the new caching API.

### CODE REVIEW

**Comment by sebersole** [comment]
Yes, we have only been focusing on hibernate-core so far on 6.  So long as core builds we are good.  Did the tests in core run successfully with this?

**Comment by gsmet** [comment]
This is for 5.3.

The core tests are running fine.

The failure I have is when building the ORM modules:
```
2017-12-14 10:51:28,132 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 62) MSC000001: Failed to start service jboss.persistenceunit."23046660-0bba-482c-b63d-ab0e6ad4cb65.war#primary": org.jboss.msc.service.StartException in service jboss.persistenceunit."23046660-0bba-482c-b63d-ab0e6ad4cb65.war#primary": javax.persistence.PersistenceException: [PersistenceUnit: primary] Unable to build Hibernate SessionFactory
        at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:195)
        at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:125)
        at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:640)
        at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:209)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: primary] Unable to build Hibernate SessionFactory
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:970)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:895)
        at org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
        at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:167)
        ... 7 more
Caused by: org.hibernate.cache.spi.access.UnknownAccessTypeException: Unknown access type [NONE]
        at org.hibernate.cache.spi.access.AccessType.fromExternalName(AccessType.java:81)
        at org.hibernate.internal.CacheImpl.determineEntityRegionAccessStrategy(CacheImpl.java:448)
        at org.hibernate.metamodel.internal.MetamodelImpl.initialize(MetamodelImpl.java:120)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:301)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:532)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
        ... 9 more
```

so I don't think it's related.

**Comment by Naros** [comment]
@gsmet @sebersole I just pushed a fix to the hibernate-orm master repository that fixes that problem.

**Comment by gsmet** [comment]
Closing. Moving it to the official repository as it's now the home of 5.3.

**Comment by sebersole** [comment]
@gsmet Is there a PR for this against master?

**Comment by gsmet** [comment]
Not yet. I spotted an issue when upgrading RESTEasy and I'm in the process of releasing a new version of the API. I thought I might as well use this one for the ORM upgrade.

**Comment by sebersole** [comment]
No problem.  I'll look for it

**Pull request closed without merging**
